FROM maven:3.9-amazoncorretto-25-alpine AS builder

WORKDIR /app

COPY src src
COPY pom.xml .

RUN mvn clean package

FROM amazoncorretto:25-alpine-jdk

WORKDIR /app

# Копируем собранный JAR из стадии builder
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]